#!/bin/bash
if [ -f {{pid_file}} ]; then
  echo "Update process is already running"
  exit 1
fi

echo $$ > {{pid_file}}

source {{env_bin}}/conda-mirror \
  --upstream-channel {{upstream_channel}} \
  --target-directory {{target_dir}} \
  --temp-directory {{temp_dir}} \
  --platform {{platform}} \
  --num-threads {{threads}}

rm {{pid_file}}
